=== bf108/causaly_data_engineering_task/data/nlmmeetingabstractset_120101.dtd
<!-- NLMMeetingAbstract DTD


     Comments and suggestions are welcome.
     January  1, 2012

    Revised: July 26, 2011

     This is the DTD which the U.S. National Library of Medicine
     has written for Internal Use.

      Export DTD


     NOTE:  The use of "Medline" in a DTD or element name does not mean the record
    represents a citation from a Medline-selected journal.  When the NLM DTDs and
    XML elements were first created, MEDLINE records were the only data exported.
    Now NLM exports citations other than MEDLINE records using these tools. To
    minimize unnecessary disruption to users of the data and tools, NLM has
    retained the original DTD and element names (e.g., MedlineDate, MedlineTA,
    MedlineJournalInfo, MedlinePgn)).

    NOTE:  StartPage and EndPage in Pagination element are not currently used;
           are reserved for future use.

* = 0 or more occurrences (optional element, repeatable)
? = 0 or 1 occurrences (optional element, at most 1)
+ = 1 or more occurrences (required element, repeatable)
| = choice, one or the other but not both
no symbol = required element

       -->
<!-- ================================================================= -->
<!---  Revision Notes Section                                          -->
<!--
    The following changes were made:

        a. Changed nlmmeetingabstractset_110101.dtd to
           nlmmeetingabstractset_120101.dtd
        b. Added new KeywordList Owner attribute valid value HHS.

   -->
<!-- ================================================================= -->
<!ELEMENT Abstract (AbstractText,CopyrightInformation?)>
<!ELEMENT AbstractText (#PCDATA)>
<!ELEMENT AccessionNumber (#PCDATA)>
<!ELEMENT AccessionNumberList (AccessionNumber+)>
<!ELEMENT Acronym (#PCDATA)>
<!ELEMENT Affiliation (#PCDATA)>
<!ELEMENT Agency (#PCDATA)>
<!ELEMENT Article (Journal, ArticleTitle?, ((Pagination, ELocationID*) | ELocationID+), Abstract?, Affiliation?, AuthorList?, Language+, DataBankList?, GrantList?, PublicationTypeList, VernacularTitle?, ArticleDate*)>
<!ATTLIST Article PubModel (Print | Print-Electronic | Electronic | Electronic-Print) #REQUIRED>
<!ELEMENT ArticleDate (Year,Month?,Day?)>
<!ATTLIST ArticleDate DateType CDATA  #FIXED "Electronic">
<!ELEMENT ArticleTitle (#PCDATA)>
<!ELEMENT Author (((LastName,ForeName?, Initials?,Suffix?) | CollectiveName), Affiliation?, OtherInformation?)>
<!ATTLIST Author ValidYN (Y | N) "Y">
<!ELEMENT AuthorList (Author+)>
<!ATTLIST AuthorList CompleteYN (Y | N) "Y">
<!ELEMENT CitationSubset (#PCDATA)>
<!ELEMENT CollectiveName (#PCDATA)>
<!ELEMENT CopyrightInformation (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT DataBank (DataBankName, AccessionNumberList?)>
<!ELEMENT DataBankList (DataBank+)>
<!ATTLIST DataBankList CompleteYN (Y | N) "Y">
<!ELEMENT DataBankName (#PCDATA)>
<!ELEMENT DateCompleted (Year,Month,Day)>
<!ELEMENT DateCreated (Year,Month,Day)>
<!ELEMENT DateRevised (Year,Month,Day)>
<!ELEMENT Day (#PCDATA)>
<!ELEMENT DeleteMeetingAbstract (NlmDcmsID+)>
<!ELEMENT ELocationID (#PCDATA)>
<!ATTLIST ELocationID EIdType (doi | pii) #REQUIRED ValidYN  (Y | N) "Y">
<!ELEMENT EndPage (#PCDATA)>
<!ELEMENT ForeName (#PCDATA)>
<!ELEMENT GeneSymbol (#PCDATA)>
<!ELEMENT GeneSymbolList (GeneSymbol+)>
<!ELEMENT GeneralNote (#PCDATA)>
<!ATTLIST GeneralNote Owner (AIDS | NLM | NASA | HMA | NOTNLM | LHC) "NLM">
<!ELEMENT Grant (GrantID?, Acronym?, Agency?, Country)>
<!ELEMENT GrantID (#PCDATA)>
<!ELEMENT GrantList (Grant+)>
<!ATTLIST GrantList CompleteYN (Y | N) "Y">
<!ELEMENT ISOAbbreviation (#PCDATA)>
<!ELEMENT ISSN (#PCDATA)>
<!ATTLIST ISSN IssnType  (Electronic | Print | Undetermined) #REQUIRED>
<!ELEMENT ISSNLinking (#PCDATA)>
<!ELEMENT Initials (#PCDATA)>
<!ELEMENT Investigator (LastName,ForeName?, Initials?,Suffix?, Affiliation?)>
<!ATTLIST Investigator ValidYN (Y | N) "Y">
<!ELEMENT InvestigatorList (Investigator+)>
<!ELEMENT Issue (#PCDATA)>
<!ELEMENT Journal (ISSN?, JournalIssue, Title?, ISOAbbreviation?)>
<!ELEMENT JournalIssue (Volume?, Issue?, PubDate)>
<!ATTLIST JournalIssue CitedMedium (Internet | Print) #REQUIRED>
<!ELEMENT Keyword (#PCDATA)>
<!ATTLIST Keyword MajorTopicYN (Y | N) "N">
<!ELEMENT KeywordList (Keyword+)>
<!ATTLIST KeywordList Owner (AIDS | NLM | NLM-AUTO | NASA | HMA | NOTNLM | HHS) "NLM">
<!ELEMENT Language (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT MedlineDate (#PCDATA)>
<!ELEMENT MedlineJournalInfo (Country?, MedlineTA, NlmUniqueID?, ISSNLinking?)>
<!ELEMENT MedlinePgn (#PCDATA)>
<!ELEMENT MedlineTA (#PCDATA)>
<!ELEMENT Month (#PCDATA)>
<!ELEMENT NlmDcmsID (#PCDATA)>
<!ELEMENT NlmUniqueID (#PCDATA)>
<!ELEMENT OtherAbstract (AbstractText,CopyrightInformation?)>
<!ATTLIST OtherAbstract Type (AIDS | NASA | Undetermined) #REQUIRED>
<!ELEMENT OtherID (#PCDATA)>
<!ATTLIST OtherID Source (LHC | NASA | NLM | HMA) #REQUIRED>
<!ELEMENT OtherInformation (#PCDATA)>
<!ELEMENT Pagination ((StartPage, EndPage?, MedlinePgn?) | MedlinePgn)>
<!ELEMENT PersonalNameSubject (LastName,ForeName?, Initials?,Suffix?)>
<!ELEMENT PersonalNameSubjectList (PersonalNameSubject+)>
<!ELEMENT PubDate ((Year, ((Month, Day?) | Season)?) | MedlineDate)>
<!ELEMENT PublicationType (#PCDATA)>
<!ELEMENT PublicationTypeList (PublicationType+)>
<!ELEMENT Season (#PCDATA)>
<!ELEMENT SpaceFlightMission (#PCDATA)>
<!ELEMENT StartPage (#PCDATA)>
<!ELEMENT Suffix (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT VernacularTitle (#PCDATA)>
<!ELEMENT Volume (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
<!--	MeetingAbstractSet	-->
<!ELEMENT MeetingAbstractSet (MeetingAbstract*, DeleteMeetingAbstract?)>
<!ELEMENT MeetingAbstract (NlmDcmsID, DateCreated, DateCompleted?, DateRevised?, Article, MedlineJournalInfo, CitationSubset*, GeneSymbolList?, OtherID*, OtherAbstract*, PersonalNameSubjectList?, KeywordList*, SpaceFlightMission*, InvestigatorList?, GeneralNote*)>
<!ATTLIST MeetingAbstract Owner (AIDS | NLM | NASA | HMA | NOTNLM | LHC) "NLM" Status (In-Process | Completed)  #REQUIRED>

=== bf108/causaly_data_engineering_task/tests/data/dummy.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE MeetingAbstractSet
        PUBLIC "-//NLM//DTD MeetingAbstract, 1st January, 2012//EN" "https://www.nlm.nih.gov/databases/dtd/nlmmeetingabstractset_120101.dtd">
<MeetingAbstractSet>
    <MeetingAbstract Owner="NASA" Status="Completed">
        <NlmDcmsID>102184889</NlmDcmsID>
        <DateCreated>
            <Year>2000</Year>
            <Month>02</Month>
            <Day>24</Day>
        </DateCreated>
        <DateCompleted>
            <Year>2000</Year>
            <Month>03</Month>
            <Day>01</Day>
        </DateCompleted>
        <Article PubModel="Print">
            <Journal>
                <ISSN IssnType="Print">0016-5085</ISSN>
                <JournalIssue CitedMedium="Print">
                    <Volume>116</Volume>
                    <Issue>4 Pt 2</Issue>
                    <PubDate>
                        <Year>1999</Year>
                        <Month>Apr</Month>
                    </PubDate>
                </JournalIssue>
                <Title>Gastroenterology</Title>
                <ISOAbbreviation>Gastroenterology</ISOAbbreviation>
            </Journal>
            <ArticleTitle>The virtual esophagus: a new tool for examination of esophageal motility.</ArticleTitle>
            <Pagination>
                <MedlinePgn>A1060</MedlinePgn>
            </Pagination>
            <Abstract>
                <AbstractText>INTRODUCTlON: Alterations of normal esophageal motility are involved in a variety of clinical disorders that may be categorized into two broad classes: hypermotility disorders and hypomotility disorders. Esophageal motility disorders can be understood as hyper/hypo-states of normal esophageal physiological function. This study proposes a virtual reality simulation of esophageal motility that will enhance our understanding of the geometry and biomechanics of physiological and pathophysiological states of the esophagus. METHODS: The development of a time dependent 3-dimensional computer simulation of esophageal motility was performed in two phases. Phase 1 included the 3-dimensional reconstruction of the National Library of Medicine's Visible Male GI tract. ROSS software developed by NASA Ames Bioinformatics Center was used to produce the surface reconstruction of the esophagus. The reconstruction extends from the upper esophageal sphincter (UES) to the lower esophageal sphincter (LES). Phase 2 involved application of experimentally based motility equations to the reconstruction to simulate esophageal peristaltic motion. Modifications of the equations that describe motion allow for the simulation of anamolous states of motility. RESULTS: A video of an anatomically accurate model of esophageal motility which allows for the visualization and study of biomechanical function in the esophagus will be presented. CONCLUSION: The interactive 3-dimensional simulation will serve as a useful tool in the study of esophageal disease states. For instance, the simulation could be used to reduce tone in the LES to simulate GERD or to couple increased tone in the esophageal wall with decreased motility to simulate achalasia. The simulation may also be applied as a tool to enhance GI anatomical/physiological education and to the study of the effects of aging and weightlessness on esophageal function.</AbstractText>
            </Abstract>
            <Affiliation>Univ of Arkansas for Med Sci, Little Rock, USA.</Affiliation>
            <AuthorList CompleteYN="Y">
                <Author ValidYN="Y">
                    <LastName>Pasley</LastName>
                    <ForeName>J N</ForeName>
                    <Initials>JN</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Sumpter</LastName>
                    <ForeName>J A</ForeName>
                    <Initials>JA</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Compadre</LastName>
                    <ForeName>C M</ForeName>
                    <Initials>CM</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Ross</LastName>
                    <ForeName>M D</ForeName>
                    <Initials>MD</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Breen</LastName>
                    <ForeName>P J</ForeName>
                    <Initials>PJ</Initials>
                </Author>
            </AuthorList>
            <Language>eng</Language>
            <PublicationTypeList>
                <PublicationType>Meeting Abstracts</PublicationType>
            </PublicationTypeList>
        </Article>
        <MedlineJournalInfo>
            <Country>United States</Country>
            <MedlineTA>Gastroenterology</MedlineTA>
            <NlmUniqueID>0374630</NlmUniqueID>
            <ISSNLinking>0016-5085</ISSNLinking>
        </MedlineJournalInfo>
        <CitationSubset>S</CitationSubset>
        <OtherID Source="LHC">20600308</OtherID>
        <OtherID Source="NASA">NASA/00024699</OtherID>
        <KeywordList Owner="NASA">
            <Keyword MajorTopicYN="N">NASA Center ARC</Keyword>
            <Keyword MajorTopicYN="N">NASA Discipline Neuroscience</Keyword>
        </KeywordList>
        <KeywordList Owner="NLM-AUTO">
            <Keyword MajorTopicYN="N">Esophageal Achalasia</Keyword>
            <Keyword MajorTopicYN="N">Esophageal Diseases</Keyword>
            <Keyword MajorTopicYN="N">Esophageal Motility Disorders</Keyword>
            <Keyword MajorTopicYN="N">Esophageal Sphincter, Lower</Keyword>
            <Keyword MajorTopicYN="N">Esophageal Sphincter, Upper</Keyword>
            <Keyword MajorTopicYN="N">Esophagus</Keyword>
            <Keyword MajorTopicYN="N">Gastroesophageal Reflux</Keyword>
            <Keyword MajorTopicYN="N">Gastrointestinal Tract</Keyword>
            <Keyword MajorTopicYN="N">Humans</Keyword>
            <Keyword MajorTopicYN="N">Male</Keyword>
            <Keyword MajorTopicYN="N">Obesity, Morbid</Keyword>
            <Keyword MajorTopicYN="N">Peristalsis</Keyword>
            <Keyword MajorTopicYN="N">Physical Examination</Keyword>
        </KeywordList>
        <InvestigatorList>
            <Investigator ValidYN="Y">
                <LastName>Ross</LastName>
                <ForeName>M D</ForeName>
                <Initials>MD</Initials>
                <Affiliation>ARC</Affiliation>
            </Investigator>
        </InvestigatorList>
        <GeneralNote Owner="NASA">Meeting held in: United States</GeneralNote>
    </MeetingAbstract>
</MeetingAbstractSet>
